[package]
name = "nano_drum"
version = "0.1.0"
authors = ["uma <blog3170@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.5.0"
rodio = "0.9.0"